name: Sync Engine with Dependency

on:
  push:
    branches:
      - "**"
    paths:
      - 'package.json'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Sync engine version
        run: |
          node scripts/syncPackageEngineWithDependency.mjs vscode @types/vscode

      - name: Commit if changed
        id: commit
        continue-on-error: true
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json
          git commit -m "chore: sync vscode engine version with dependency"

      - name: push
        if: steps.commit.outcome != 'failure'
        run: git push
